apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  index.html: |
    <h1>{{ .Values.mensaje }}</h1>
    <p>Imagen: {{ .Values.image.repository }}:{{ .Values.image.tag }}</p>
    <p>Replicas: {{ .Values.replicaCount }}</p>
